### ISSUE TITLE
老哥你最新的版本usb没问题吗

### ISSUE THREAD

**Issue by Teng** [Sharlion/z170_6700k_hackintosh#12]
奇怪的,我3.0设备不行,插2.0设备就可以识别,同一个口

**Comment by Sharlion** [comment]
> 奇怪的,我3.0设备不行,插2.0设备就可以识别,同一个口

没问题，10.15重新定制了usb端口，你可以看看我的commit

**Comment by Teng** [comment]
@Sharlion 用的就是最新的.那就奇怪了,我的也是ASUS z170p + 6700k

**Comment by Teng** [comment]
就更新了一下,支持硬解的那个

**Comment by Sharlion** [comment]
> 奇怪的,我3.0设备不行,插2.0设备就可以识别,同一个口

用hackintool定制下把

**Comment by Teng** [comment]
usb我通过定制解决了.
发现另一个问题,最新的支持硬解的efi,开机第二阶段会有一瞬间花屏(苹果撕裂).以前的efi是黑屏1s.
(使用的核显,独显不清楚) @Sharlion

**Comment by Sharlion** [comment]
> usb我通过定制解决了.
> 发现另一个问题,最新的支持硬解的efi,开机第二阶段会有一瞬间花屏(苹果撕裂).以前的efi是黑屏1s.
> (使用的核显,独显不清楚) @Sharlion

这个。。。不清楚了，我是独显，第二阶段会黑屏1s左右，核显没有研究，一直用的独显；支持硬解的只是改了机型信息，其他没动
