### ISSUE TITLE
老哥已经用上10.15 catalina了吗

### ISSUE THREAD

**Issue by Teng** [Sharlion/z170_6700k_hackintosh#8]
@Sharlion  有发现什么问题吗,你是直接升级的吗,还是全新安装

**Comment by Sharlion** [comment]
嗯，用上了，直接升级的，需要更新的文件都已经在commit里面显示了

**Comment by Sharlion** [comment]
问题嘛，好像usb3.0有点问题，有时间了看看是哪里出问题了，其他暂时没发现

**Comment by luoqiangboy** [comment]
我的z170x ud3  6700k  588  配置可以直接用你的efi嘛？

**Comment by Sharlion** [comment]
> 我的z170x ud3 6700k 588 配置可以直接用你的efi嘛？

可以用，但是声卡、网卡、usb可能需要调整

**Comment by Sharlion** [comment]
> @Sharlion 有发现什么问题吗,你是直接升级的吗,还是全新安装

嗯，用上了，直接升级的，需要更新的文件都已经在commit里面显示了
问题嘛，好像usb3.0有点问题，不过也已经修复了

**Comment by luoqiangboy** [comment]
其他的config 这些需要调整么？ 老哥有联系方式没 给个呗

**Comment by Teng** [comment]
> > @Sharlion 有发现什么问题吗,你是直接升级的吗,还是全新安装
> 
> 嗯，用上了，直接升级的，需要更新的文件都已经在commit里面显示了
> 问题嘛，好像usb3.0有点问题，不过也已经修复了

话说你的可以睡眠吗,我的几个macos版本都是睡眠无法唤醒(显示器无显示,机器有动静).我之前尝试了usb定制.我的和你的就相差一个显卡,你的可以吗? @Sharlion

**Comment by Sharlion** [comment]
> > > @Sharlion 有发现什么问题吗,你是直接升级的吗,还是全新安装
> > 
> > 
> > 嗯，用上了，直接升级的，需要更新的文件都已经在commit里面显示了
> > 问题嘛，好像usb3.0有点问题，不过也已经修复了
> 
> 话说你的可以睡眠吗,我的几个macos版本都是睡眠无法唤醒(显示器无显示,机器有动静).我之前尝试了usb定制.我的和你的就相差一个显卡,你的可以吗? @Sharlion

睡眠正常，没发现问题
